on: [push, pull_request]

jobs:
  lint:
    name: Clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install clang-format
      - name: Run clang-format
        run: clang-format $(find src -type f) --dry-run -Werror
  build:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [clang++, g++]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install build-essential libsfml-dev
      - name: Build
        run: make CC=${{ matrix.cc }}
